name: rdit_env
channels:
  - conda-forge
  - defaults
dependencies:
  # Python setup
  - python=3.10.16
  - numpy
  - pandas
  - pip
  - pip:
      - rdpower==1.0.1
      - rdrobust==1.1.1

  # R setup
  - r-base=4.3.3
  - r-tidyverse=2.0.0
  - r-data.table=1.16.4
  - r-remotes=2.4.2.1
